name: RxPlayer Tests

on:
  push:
    branches: [stable, dev, legacy-v3]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: npm ci
      - run: rustup target add wasm32-unknown-unknown
      - run: npm run fmt:prettier:check
      - run: npm run fmt:rust:check

  typechecking_and_linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run check

  unit_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test:unit

  integration_linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      # needed for integration & memory tests codecs support
      - run:
          sudo add-apt-repository multiverse && sudo apt update && sudo apt install -y
          ubuntu-restricted-extras
      - run: npm ci
      - run: npm run build
      - run:
          npm run test:integration:chrome && npm run test:integration:firefox && npm run
          test:integration:edge

  integration_windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - shell: bash
        run: |
          npm ci
          npm run build
          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge

  integration_mac_safari:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: |
          npm ci
          npm run build
          npm run test:integration:safari

  integration_mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: |
          npm ci
          npm run build
          npm run test:integration:chrome && npm run test:integration:firefox && npm run test:integration:edge

  memory_linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      # needed for integration & memory tests codecs support
      - run:
          sudo add-apt-repository multiverse && sudo apt update && sudo apt install -y
          ubuntu-restricted-extras
      - run: npm ci
      - run: npm run test:memory
